WIP [10.0][ADD] Add deleter for connector_search_engine
akretion/connector-search-engine pull request #31
Opened 2018-11-12 15:04 UTC by acsonefho

- [ ] Add a deleter for the connector_search_engine module

2018-12-10 18:31 UTC, sebastienbeau commented
can you add test please?

2018-12-16 19:23 UTC, simahawk commented
@sebastienbeau if @acsonefho tested this manually and it works I think we should merge it w/ no tests as I'm writing them from scratch in the mig to v12 and they can be easily backported.
We gonna save some headache and time ;)

2018-12-16 19:29 UTC, simahawk requested changes

2018-12-16 19:29 UTC, simahawk commented on connector_search_engine/models/se_binding.py
> +        for index in self.mapped('index_id'):
I think that grouping all bindings _before_ would be easier to read and more efficient since here you are looping twice on all records. For instance:

```py
grouped_by_index = defaultdict(self.browse)
for binding in self:
    grouped_by_index[binding.index_id] += binding
for index, bindings in grouped_by_index.items():
    specific_backend = index.se_backend_id.specific_backend
    [...]
```
if you need to group on backend too, just use a tuple w/ both backend and index as a key.

2019-03-22 17:42 UTC, sebastienbeau commented
I close it as benoit have done a new PR that include this work

2019-03-22 17:42 UTC, closed without merging