WIP [10.0][connector_algolia] Improve view: inherit the se.backend view
akretion/connector-search-engine pull request #42
Opened 2019-01-04 13:59 UTC by acsonefho

Module connector_algolia
Improve view of the model by using the parent (to have automatically every fields)

2019-01-04 15:50 UTC, lmignon requested changes
@acsonefho Today I learned something new. Thank you!!!!

2019-01-04 15:50 UTC, lmignon commented on connector_algolia/views/se_backend_algolia.xml
> +        <!--Mandatory to use the view when inherited (cfr product.template and product.product)-->
@acsonefho s/Mandatory to use the view/Mandatory to use the mode/

A better explanation...

```Defining a view using the mode primary in conjunction with the inherit_id field allows to define a new view for the specified model by inheriting of an existing one defined for an other model. (by default mode value is extension```

2019-01-07 10:26 UTC, Cedric-Pigeon approved these changes

2019-01-07 10:43 UTC, lmignon approved these changes

2019-03-27 07:23 UTC, merged